# Este workflow manual se encarga de publicar el sdk a npm.
name: Publish to npm

# Se ejecuta manualmente mediante un workflow dispatch.
on:
 workflow_dispatch:

# Consiste de dos jobs..
jobs:
  # El job build ejecuta los tests y el linter.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd sdk
          npm install
          npm run linter
          npm run testCoverage

  # El job publish-npm publica el sdk a npm,
  # utilizando una token de acceso como método de autenticación.
  publish-npm:
    # Se deben haber ejecutado los tests y el linter exitosamente antes de poder publicar.
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          cd sdk
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
